### ISSUE TITLE
UI for create user page

### ISSUE THREAD

**Issue by phongnhat19** [phongnhat19/edoc-healthcare-web#11]
## Fields
| Name | Type | Description |
|--|--|--|
| name | input | User's name |
| role | dropdown | 0 (admin), 1 (organization), 2 (staff), 3 (personal user) |
| email | input | User's email |
| password | input | User's password |
| address | input | User's address |
| gender | dropdown | User's gender (Male, Female, Other) |
| yearOfBirth | dropdown | User's year of birth |
## Buttons
| Name | Action |
|--|--|
| Tạo | Call API to create User (**pending**) |
| Huỷ | Go back to user list page |

**Comment by unhang** [comment]
total:
1.5h
