### ISSUE TITLE
Create activity for doc

### ISSUE THREAD

**Issue by phongnhat19** [phongnhat19/edoc-healthcare-web#23]
# DoD

- [x] UI: Model for create new doc's activity
- [x] API: integrate create activity API

### UI
Based on API `Add Act - get raw TX`, create activity modal consist of:
| Field | Type | Label | Description
|--|--|--|--
| name | string | Nội dung | Summary of activity information
| recordingTime | string | Thời gian | Activity time (automatically)
| recordingPerson | string | Người cấp | Information of recording person
| recordingPlace | string | Người cấp | Information of recording organization
| status | object |  | Activity status
| status.name | string | Trạng thái | Status name
| status.backgroundColor | string (ColorPicker) | Màu nền | Status background color
| images | object[] | Hình ảnh | Activity image
| images[].title | string | Tiêu đề | Image title
| images[].url | string |  | Image URL. User can input their custom URL or use ImagePicker to upload their image (upload to cloudinary).
| note | string (Text Area) | Ghi chú | Activity note
| description | object[] | Mô tả | Activity description
| description[].key | string | Thông tin | Description key
| description[].value | string | Gía trị | Description value

### API
Reference to `getFormRawTX`, `sendSignedFormTX` in `services/api/form.ts` and `sendSignedFormTX` in `page/Forms/CreateForm/index.tsx`, create 2 functions `getActivityRawTX` and `sendSignedActivityTX`.

Flow: 
1. Validate form
2. Call `getActivityRawTX` to get `rawTX`
3. Use `symDecrypt` to get decrypted private key
4. Use `getSignedTx` and `rawTX` to get `signedTX`
5. Call `sendSignedActivityTX`

**Comment by unhang** [comment]
API secret là B87ja14Won1J451FhTiIOUq0MYQ
API key 776754227374745
API enviroment varible CLOUDINARY_URL=cloudinary://776754227374745:B87ja14Won1J451FhTiIOUq0MYQ@agridential

**Comment by unhang** [comment]
UI done
total:
4h
