### ISSUE TITLE
Integrate create user API

### ISSUE THREAD

**Issue by phongnhat19** [phongnhat19/edoc-healthcare-web#26]
# Integrate create staff user API
Reference: [Postman documents](https://documenter.getpostman.com/view/2051357/SzmmTtgY?version=latest#e722d501-935e-4447-9977-1fcc48a26c28)

**Note**
- For `staff` user, field `username` is required. For other type of user, integrate other API.
- To generate `bcAddress`, use `generateEOA` function from `blockchain.ts` util:
	```
	const userEOA = generateEOA();
	const bcAddress = userEOA.address;
	```
- To generate `privateEncrypted`, use `generateEOA` function from `blockchain.ts` util:
	```
	const userEOA = generateEOA();
	const {privateKey} = userEOA;

	const clientPassphrase = 'my_password_hash'; // Currently client passphrase will be 'my_password_hash' for every user
	const privateEncrypted = symEncrypt(privateKey, clientPassphrase);
	```

**Comment by unhang** [comment]
total:
1h

**Comment by phongnhat19** [comment]
# Additional requirement
Integrate sign up API for `personal` and `organization` user. [API doc](https://documenter.getpostman.com/view/2051357/SzmmTtgY?version=latest#3f80723d-6c0f-4752-b9bb-f2d46bd5149b)

Params
| Field | Type | Description
|--|--|--|
| name | string | User's name
| email | string | User's email
| password | string | User's password
| bcAddress | string | User's blockchain address
| privateEncrypted | string | User's encrypted private key
| recaptchaToken | string | reCAPTCHA token get from Google reCAPTCHA

> Note:
> Use `password` as `clientPassphrase`
